/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tempo;

import java.applet.AudioClip;
import static java.lang.Thread.sleep;
import ruta.CancionRuta;
/**
 *
 * @author DanKuzo
 */
public class proyecto extends javax.swing.JPanel {
    CancionRuta cancionR = new CancionRuta();
    Thread thread;

    /**
     * Creates new form proyecto
     */
    public proyecto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        min = new javax.swing.JTextField();
        seg = new javax.swing.JTextField();
        iniciarPausar = new javax.swing.JButton();
        reinicio = new javax.swing.JButton();

        jLabel1.setText("Minutos:");

        jLabel2.setText("Segundos:");

        iniciarPausar.setText("Iniciar");
        iniciarPausar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarPausarActionPerformed(evt);
            }
        });

        reinicio.setText("Reiniciar");
        reinicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reinicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(iniciarPausar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(min, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seg, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reinicio))
                .addGap(0, 68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iniciarPausar)
                    .addComponent(reinicio)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarPausarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarPausarActionPerformed
        inicio();
    }//GEN-LAST:event_iniciarPausarActionPerformed

    private void reinicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reinicioActionPerformed
        reset();
    }//GEN-LAST:event_reinicioActionPerformed
    private void inicio() {
        thread = new Thread() {
            @Override
            public void run() {
                int minutos = Integer.parseInt(min.getText());
                int segundos = Integer.parseInt(seg.getText());
                min.setEditable(false);
                seg.setEditable(false);
                iniciarPausar.setEnabled(false);

                for (int i = minutos; i >= 0; i--) {
                    min.setText(String.valueOf(i));
                    for (int j = segundos; j >= 0; j--) {
                        seg.setText(String.valueOf(j));
                        try {
                            sleep(1000);
                        } catch (InterruptedException e) {
                        }
                    }
                    segundos = 59;
                }
                cancion();
                min.setEditable(true);
                seg.setEditable(true);
                iniciarPausar.setEnabled(true);
            }

        };

        thread.start();

    }

    private void reset() {
        min.setEditable(true);
        seg.setEditable(true);
        iniciarPausar.setEnabled(true);
        seg.setText("0");
        min.setText("0");
        thread.stop();
        cancionR.cancionDetener();
    }

    public void cancion() {
        cancionR.cancionReproducir();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton iniciarPausar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField min;
    private javax.swing.JButton reinicio;
    private javax.swing.JTextField seg;
    // End of variables declaration//GEN-END:variables
}
